[package]
name = "guardctl"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
guard-ipc.workspace = true
guard-client.workspace = true
guard-platform.workspace = true
guard-core.workspace = true
guard-ssh.workspace = true
anyhow.workspace = true
clap.workspace = true
libc.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
platform-linux.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
platform-macos.workspace = true
