[package]
name = "guard-tui"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
guard-ipc.workspace = true
platform-linux.workspace = true
serde_json.workspace = true
ratatui.workspace = true
crossterm.workspace = true

[lib]
name = "guard_tui"
path = "src/lib.rs"

[[bin]]
name = "guard-tui"
path = "src/main.rs"

[dev-dependencies]
tempfile.workspace = true
guard-ipc.workspace = true
