[package]
name = "guard-notify"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
guard-ipc.workspace = true
guard-client.workspace = true
clap.workspace = true
serde_json.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
platform-macos.workspace = true
