[package]
name = "platform-linux"
version.workspace = true
edition.workspace = true
license.workspace = true
build = "build.rs"

[dependencies]
guard-core.workspace = true
libc.workspace = true
tracing.workspace = true
thiserror.workspace = true
serde.workspace = true
anyhow.workspace = true
sha2.workspace = true
serde_json.workspace = true
cap-std.workspace = true

[dev-dependencies]
tempfile.workspace = true
